#!/bin/bash
# build-core.sh - Builds libschwungcore.a (QuickJS + unmodified schwung shadow UI
# sources + Apple compat layer) for macOS arm64, plus the font assets.
set -e

NATIVE_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$NATIVE_DIR/../git-schwung"
BUILD_DIR="$NATIVE_DIR/build"

# TARGET=macos (default) or iossim — separate object/output dirs per target.
TARGET="${TARGET:-macos}"
case "$TARGET" in
    macos)
        TARGET_FLAGS="-arch arm64"
        OUT_DIR="$BUILD_DIR"
        ;;
    iossim)
        SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"
        TARGET_FLAGS="-target arm64-apple-ios16.0-simulator -isysroot $SDK"
        OUT_DIR="$BUILD_DIR/iossim"
        ;;
    ios)
        SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
        TARGET_FLAGS="-target arm64-apple-ios16.0 -isysroot $SDK"
        OUT_DIR="$BUILD_DIR/ios"
        ;;
    *) echo "unknown TARGET=$TARGET"; exit 1 ;;
esac

OBJ_DIR="$OUT_DIR/obj"
QJS_TARBALL="$REPO_DIR/libs/quickjs/quickjs-2025-04-26.tar.xz"
QJS_DIR="$BUILD_DIR/quickjs-2025-04-26"

mkdir -p "$OBJ_DIR"

# --- Extract QuickJS (unmodified upstream tarball) ---
if [ ! -d "$QJS_DIR" ]; then
    echo "Extracting QuickJS..."
    tar xf "$QJS_TARBALL" -C "$BUILD_DIR"
fi

CC=clang
COMMON_FLAGS="-O2 -g $TARGET_FLAGS -fno-common -Wno-deprecated-declarations"
QJS_DEFS="-D_GNU_SOURCE -DCONFIG_VERSION=\"2025-04-26\""
INCLUDES="-I$QJS_DIR -I$REPO_DIR/src -I$REPO_DIR/src/lib -I$REPO_DIR/src/host -I$NATIVE_DIR -I$NATIVE_DIR/shim-include"
OVERRIDE="-include $NATIVE_DIR/apple_compat_overrides.h"

compile() { # out.o, src.c, extra flags...
    local out="$OBJ_DIR/$1"; local src="$2"; shift 2
    if [ "$out" -nt "$src" ] && [ "$out" -nt "$NATIVE_DIR/apple_compat_overrides.h" ]; then
        return
    fi
    echo "CC $(basename "$src")"
    $CC $COMMON_FLAGS $INCLUDES -c "$src" -o "$out" "$@"
}

# QuickJS core (no path remapping needed — never touches /data paths itself)
compile quickjs.o      "$QJS_DIR/quickjs.c"      $QJS_DEFS
compile libregexp.o    "$QJS_DIR/libregexp.c"    $QJS_DEFS
compile libunicode.o   "$QJS_DIR/libunicode.c"   $QJS_DEFS
compile cutils.o       "$QJS_DIR/cutils.c"       $QJS_DEFS
compile dtoa.o         "$QJS_DIR/dtoa.c"         $QJS_DEFS
# quickjs-libc resolves ES module imports via fopen → needs path remapping
compile quickjs-libc.o "$QJS_DIR/quickjs-libc.c" $QJS_DEFS $OVERRIDE

# Unmodified schwung sources, with remapping + renamed entry point
compile shadow_ui.o    "$REPO_DIR/src/shadow/shadow_ui.c" $OVERRIDE -Dmain=schwung_shadow_ui_main
compile js_display.o   "$REPO_DIR/src/host/js_display.c"  $OVERRIDE
compile unified_log.o  "$REPO_DIR/src/host/unified_log.c" $OVERRIDE
compile analytics.o    "$REPO_DIR/src/host/analytics.c"   $OVERRIDE

# Apple compat layer + audio engine (real libc, no overrides)
compile apple_compat.o "$NATIVE_DIR/apple_compat.c"
compile apple_audio_engine.o "$NATIVE_DIR/apple_audio_engine.c"

echo "AR libschwungcore.a"
ar rcs "$OUT_DIR/libschwungcore.a" "$OBJ_DIR"/*.o

# --- Module DSP dylibs (Mach-O, but named dsp.so to match upstream layout).
# -undefined dynamic_lookup: schwung_compat_* path wrappers resolve from the
# host app at load time.
DYLIB_FLAGS="-dynamiclib -undefined dynamic_lookup"

build_dsp() { # out-subdir, sources...
    local sub="$1"; shift
    local out="$OUT_DIR/modules/$sub/dsp.so"
    mkdir -p "$(dirname "$out")"
    if [ -f "$out" ]; then
        local newer=0
        for src in "$@"; do [ "$src" -nt "$out" ] && newer=1; done
        [ "$newer" = 0 ] && [ "$NATIVE_DIR/apple_compat_overrides.h" -ot "$out" ] && return
    fi
    echo "DSP $sub"
    $CC $COMMON_FLAGS $INCLUDES $DYLIB_FLAGS $OVERRIDE "$@" -o "$out" -lm -lpthread
}

build_dsp chain "$REPO_DIR/src/modules/chain/dsp/chain_host.c" "$REPO_DIR/src/host/unified_log.c"
build_dsp audio_fx/freeverb "$REPO_DIR/src/modules/audio_fx/freeverb/freeverb.c"
build_dsp midi_fx/chord "$REPO_DIR/src/modules/midi_fx/chord/dsp/chord.c"
build_dsp midi_fx/arp "$REPO_DIR/src/modules/midi_fx/arp/dsp/arp.c"
build_dsp midi_fx/velocity_scale "$REPO_DIR/src/modules/midi_fx/velocity_scale/dsp/velocity_scale.c"
build_dsp sound_generators/linein "$REPO_DIR/src/modules/sound_generators/linein/linein.c"
build_dsp tools/wav-player "$REPO_DIR/src/modules/tools/wav-player/wav_player.c"
build_dsp sound_generators/simple-synth "$NATIVE_DIR/modules/simple-synth/dsp.c"

# --- Font assets (font.png/.dat + tamzen sizes), needs Pillow. Shared across
# targets — only generated by the default macos build.
ASSETS="$BUILD_DIR/assets/host"
[ "$TARGET" != macos ] && { echo "Done: $OUT_DIR/libschwungcore.a"; exit 0; }
if [ ! -f "$ASSETS/font.png" ]; then
    echo "Generating fonts..."
    VENV="$BUILD_DIR/venv"
    if [ ! -d "$VENV" ]; then
        python3 -m venv "$VENV"
        "$VENV/bin/pip" -q install pillow
    fi
    mkdir -p "$ASSETS/fonts"
    (cd "$REPO_DIR" && "$VENV/bin/python" scripts/generate_font.py --deploy-png "$ASSETS/font.png")
    for size in 5x9 6x12 7x13 7x14 8x15 8x16 10x20; do
        height="${size#*x}"
        (cd "$REPO_DIR" && "$VENV/bin/python" scripts/generate_font.py \
            --bdf "fonts/tamzen/Tamzen${size}r.bdf" --deploy-png "$ASSETS/fonts/tamzen-${height}.png")
    done
fi

echo "Done: $OUT_DIR/libschwungcore.a"
